name: feedivo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_analytics: ^12.1.0

  # Google OAuth & Drive API
  google_sign_in: ^6.2.2
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0

  # State Management
  provider: ^6.1.5+1

  # UI & Utilities
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  url_launcher: ^6.2.4
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  timeago: ^3.6.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  pedantic_mono: ^1.28.0

flutter:

  uses-material-design: true
