name: feedivo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # ignore: sort_pub_dependencies
  cached_network_image: ^3.3.1
  chewie: ^1.8.5
  cloud_firestore: ^6.1.1
  cupertino_icons: ^1.0.8
  firebase_analytics: ^12.1.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter_spinkit: ^5.2.0
  google_sign_in: ^6.2.2
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  http: ^1.2.0
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.2
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  timeago: ^3.6.1
  url_launcher: ^6.2.4
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono: ^1.28.0

flutter:

  uses-material-design: true
